
# bag 1 contains 3 I, 1 am, and 1 Joe
bag1 <- c(3,1,1)

# Bag 2 contains 4 I, 4 am, and 2 Joe
bag2 <- c(4,4,2)


# if I reach in and draw four words (with replacement) and get the sentence "I I am am",
# what's the probability that document would have been generated by the jar?
document <- c(2,2,0)

# six permutations:
# I I am am
# I am I am
# I am am I
# am am I I
# am I am I
# am I I am

# the probability I draw that vector of words = the number of permutations times the
# probability of each word
6 * 0.6 * 0.6 * 0.2 * 0.2 # bag 1
6 * 0.4 * 0.4 * 0.4 * 0.4 # bag 2

# this is built in to R with the dmultinom() function
dmultinom(x = document, prob = bag1)

# now, what is P(document | bag2)?
dmultinom(x = document, prob = bag2)

# it's roughly twice as likely to have been generated by bag 2 as bag 1.



## Is this "statistically significant"?
## In other words, is this a likelihood ratio we wouldn't expect to observe by chance?

# Null Hypothesis: It was drawn from the mug. If we draw 10,000 documents from the mug,
# what's the probability we get a likelihood ratio in favor of the jar as large or larger
# than the one we observed?
get_lr <- function(doc){
  dmultinom(x = doc, prob = bag1) / dmultinom(x = doc, prob = bag2)
}
get_lr(document)

# draw 10,000 documents from the mug using the rmultinom() function
draws <- rmultinom(n = 10000, size = 12, prob = bag2)

simulated_likelihood_ratios <- apply(draws, 2, get_lr)

hist(simulated_likelihood_ratios)

# p-value is the probability of getting a likelihood ratio as large or larger
# than the one we observed
sum(simulated_likelihood_ratios > get_lr(document)) / length(simulated_likelihood_ratios)



## we can also look at the cosine similarity scores between these vectors.
## the most similar vectors have the smallest angle between them
# define cosine similarity
cosine_similarity <- function(x1, x2){
  sum(x1*x2) / sqrt(sum(x1^2)) / sqrt(sum(x2^2))
}

cosine_similarity(document, bag1)
cosine_similarity(document, bag2)

# the document is more similar to the jar vector than the mug vector,
# the same result we got from the multinomial model


## Draw more words! -----------------

# document of size 6
document <- c(4,2,0)
dmultinom(x = document, prob = bag1)
dmultinom(x = document, prob = bag2)

## Draw more words! --------------------

# document of size 12
document <- c(8,3,1)
dmultinom(x = document, prob = bag1)
dmultinom(x = document, prob = bag2)
get_lr(document)


